In [2]:
import json

import pandas as pd

In [3]:
with open("2-agile-augmented-gazelle/journal.json") as f:
    selected_logs = json.load(f)

In [4]:
logs_df = pd.DataFrame(selected_logs["nodes"])

In [5]:
logs_df[["is_buggy","metric","exec_time"]]

    is_buggy                                 metric   exec_time
0      False  {'value': 0.42407, 'maximize': False}    2.052711
1       True      {'value': None, 'maximize': None}    0.535269
2      False  {'value': 0.30242, 'maximize': False}    2.870023
3      False  {'value': 1.01722, 'maximize': False}    0.836274
4       True      {'value': None, 'maximize': None}    0.825942
5      False  {'value': 0.30158, 'maximize': False}    2.955862
6       True      {'value': None, 'maximize': None}    0.963651
7      False  {'value': 0.27412, 'maximize': False}   13.932979
8      False  {'value': 0.27537, 'maximize': False}   15.496966
9      False  {'value': 0.27789, 'maximize': False}   14.667102
10     False   {'value': 0.2883, 'maximize': False}    8.941941
11     False  {'value': 0.38889, 'maximize': False}    5.578154
12     False  {'value': 0.28853, 'maximize': False}   16.042492
13     False  {'value': 0.27319, 'maximize': False}   16.513745
14     False  {'value': 0.26635, 'maximize': False}   16.385720
15     False  {'value': 0.27423, 'maximize': False}   15.113175
16     False  {'value': 0.26635, 'maximize': False}   15.393709
17     False  {'value': 0.26585, 'maximize': False}   16.479230
18     False  {'value': 0.26134, 'maximize': False}   17.342351
19     False  {'value': 0.26271, 'maximize': False}   16.412175
20     False  {'value': 0.26134, 'maximize': False}   16.245053
21     False  {'value': 0.26559, 'maximize': False}   16.494239
22     False  {'value': 0.26141, 'maximize': False}   16.036304
23     False  {'value': 0.26329, 'maximize': False}   15.657358
24      True      {'value': None, 'maximize': None}    0.988389
25     False   {'value': 0.2626, 'maximize': False}   14.876130
26     False  {'value': 0.26134, 'maximize': False}   68.064847
27     False  {'value': 0.26091, 'maximize': False}   15.388553
28     False  {'value': 0.25931, 'maximize': False}   16.468160
29     False  {'value': 0.26093, 'maximize': False}   14.960914
30     False   {'value': 0.2607, 'maximize': False}   16.995784
31     False  {'value': 0.26433, 'maximize': False}   12.695394
32      True      {'value': None, 'maximize': None}  128.767006
33     False  {'value': 0.26088, 'maximize': False}  150.842923
34     False  {'value': 0.25793, 'maximize': False}   44.257917
35     False  {'value': 0.26195, 'maximize': False}   38.048436
36     False  {'value': 0.25854, 'maximize': False}   45.391606
37     False  {'value': 0.25813, 'maximize': False}   51.068738
38     False  {'value': 0.25813, 'maximize': False}   50.701616
39     False  {'value': 0.25822, 'maximize': False}  187.457783
40     False  {'value': 0.25813, 'maximize': False}   48.218478
41     False  {'value': 0.26274, 'maximize': False}   58.131168
42     False  {'value': 0.25743, 'maximize': False}   73.787491
43     False  {'value': 0.25773, 'maximize': False}   79.639103
44     False  {'value': 0.25859, 'maximize': False}   76.574809
45     False  {'value': 0.25691, 'maximize': False}   75.543357
46     False   {'value': 0.2568, 'maximize': False}   77.029557
47     False  {'value': 0.25759, 'maximize': False}   80.375135
48     False  {'value': 0.25728, 'maximize': False}   88.783832
49     False  {'value': 0.26114, 'maximize': False}   73.179711

In [6]:
logs_df.columns

Index(['code', 'plan', 'step', 'id', 'ctime', 'parent', 'children',
       '_term_out', 'exec_time', 'exc_type', 'exc_info', 'exc_stack',
       'analysis', 'metric', 'is_buggy'],
      dtype='object')

In [7]:
buggy = (logs_df["is_buggy"] == True).sum() / len(logs_df)
print("{}%".format(round(buggy * 100, 2)))

10.0%

In [8]:
logs_df["metric"].apply(lambda x: x["maximize"]).describe()

count        45
unique        1
top       False
freq         45
Name: metric, dtype: object

In [9]:
logs_df["metric"] = logs_df["metric"].apply(lambda x: x["value"])

In [10]:
pipelines_ordered_by_eval = logs_df.sort_values(by="metric", ascending=True)

In [11]:
pipelines_ordered_by_eval.head(3)

,code,plan,step,id,ctime,parent,children,_term_out,exec_time,exc_type,exc_info,exc_stack,analysis,metric,is_buggy
46,import pandas as pd\nimport numpy as np\nfrom ...,I propose adding a binary “is_weekend” feature...,46,7240007a524446a58de810690c387323,1.761564e+09,None,[],[[LightGBM] [Info] Auto-choosing col-wise mult...,77.029557,None,None,None,The training script executed successfully with...,0.25680,False
45,import pandas as pd\nimport numpy as np\nfrom ...,I propose adding LightGBM’s L1 and L2 regulari...,45,41e69c82d79f4fe4b2ca47f5198dda9b,1.761564e+09,None,[],[[LightGBM] [Info] Auto-choosing col-wise mult...,75.543357,None,None,None,The training script executed successfully with...,0.25691,False
48,import pandas as pd\nimport numpy as np\nfrom ...,I propose increasing the LightGBM model capaci...,48,4cdac18eb933466baa67c0981e655051,1.761565e+09,None,[],[[LightGBM] [Info] Auto-choosing col-wise mult...,88.783832,None,None,None,The training script executed successfully with...,0.25728,False

In [12]:
for i,code in enumerate(logs_df["code"]):
    with open(f"2-agile-augmented-gazelle/pipelines/pipeline{i}.py", "w") as f:
        f.write(code)

In [13]:
logs_df["is_buggy"]

0     False
1      True
2     False
3     False
4      True
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24     True
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32     True
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
Name: is_buggy, dtype: bool

In [14]:
logs_df.head(5)["exec_time"].sum()

7.120219469070435